config/routes.rb
Brails::Application.routes.draw do

  get "home/index"
  devise_for :users, :path_names => {
    :sign_in => 'login', 
    :sign_out => 'logout', 
    :password => 'secret', 
    :confirmation => 'verification',
    :root_path => 'home#index' 
  }

  resources :users
  resources :requests
  resources :levels do
    resources :topics 
    resources :bonus_rounds
  end  

  match '/topics/attempt_question/:question_id' => 'topics#attempt_question', as: :attempt_question
  match '/level/attempt_question/:question_id' => 'levels#attempt_bonus_question', as: :attempt_bonus_question
  match '/users/:user_id/profile' => 'users#profile', :via => [:get, :post], as: :profile
  match '/levels_list' => 'levels#levels_list', :via => :get, as: :levels_list
  match '/nominate' => 'home#nominate', :via => [:get, :post], as: :nominate
  match 'nominate_list' => 'home#nominate_list', :via => :get, as: :nominate_list
  match '/feedback' => 'home#feedback', :via => [:get, :post], as: :feedback
  match '/feedback_list' => 'home#feedback_list', :via => :get, as: :feedback_list
  put '/levels/:level_id/content/:content_id' => 'topics#remove_mp3_file', as: :remove_mp3_file
  put '/content/:content_id' => 'topics#remove_ogg_file', as: :remove_ogg_file

  root :to => 'levels#index'

  match ':action' => 'static#:action'
end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Slug


  field :title, type: String
  field :description, type: String

  slug :title

  #validation
  validates :title, :description, :level_id, :presence => true
  attr_accessible :title,  :description, :contents_attributes, :questions_attributes, :level_id

  belongs_to :level
  has_many :contents, dependent: :destroy, order: 'sq_no ASC'
  has_many :attempts
  accepts_nested_attributes_for :contents, allow_destroy: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!, :except => :show
  before_filter :load_topic, :only => [:edit, :update, :destroy, :show] 
  load_and_authorize_resource :topic, :except => :show
  
  def index
    @level = Level.find(params[:level_id])
    @topics = @level.topics
  end

  def show
    @contents = @topic.contents
  end

  def new
    @level = Level.find(params[:level_id])
    @topic = @level.topics.build
    render layout: 'admin'
  end

  def create
    @topic = Topic.new(params[:topic])
    @level = Level.find(params[:level_id])
    if @topic.save
      flash[:message] = 'Successfully created'
      redirect_to level_topics_path(@level)
    else
      render :action => :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    render layout: 'admin'
  end

  def update
    if @topic.update_attributes(params[:topic])
      flash[:message] = 'Successfully updated'
      redirect_to level_topics_path(@level)
    else
      render :action => :edit
    end
  end

  def attempt_question
    @question = Question.find(params[:question_id])
    @answer = @question.options.where(:_id => params["question"]['options']).try(:first) if params['question'].present?
    @attempt = Attempt.find_or_create_by(:user => current_user, :question => @question, :topic => @question.content.topic)
    if @answer.is_valid and @attempt.increase_count == 0
      @attempt.update_attributes({solved: true, coins: H_COOKIES[@question.question_type]})
    elsif @answer.is_valid and @attempt.increase_count > 0
      coins = (H_COOKIES[@question.question_type] / @attempt.increase_count ).round
      @attempt.update_attributes({solved: true, coins: coins})
    else
      @attempt.inc(:increase_count, 1)
    end
  end

  def destroy
    @topic.destroy
    redirect_to level_topics_path(@level)
  end

  def remove_mp3_file
    content = Content.find(params[:content_id])
    topic = content.topic
    level = Level.find(params[:level_id])
    if content.topic_content != nil
      content.topic_content.clear
      content.save
    else
      render :action => :edit
    end    
  end

  def remove_ogg_file
    content = Content.find(params[:content_id])
    topic = content.topic
    level = topic.level
    if content.content_audio != nil
      content.content_audio.clear
      content.save
    else
      render :action => :edit
    end
  end

  private
  def load_topic
    @topic = Topic.find(params[:id])
    if params[:level_id] != nil
      @level = Level.find(params[:level_id])
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
- content_for :javascript do
  = javascript_include_tag 'validations', 'topics', 'nested_form'
= simple_nested_form_for [@level, @topic], html:  {:class => 'form-horizontal'} do |f|
  = @topic.errors.full_messages

  - if !@topic.errors.empty?
    %p#errorcontainer
  .form-inputs
    = f.hidden_field :level_id
    = f.input :title
    = f.input :description, as: :text, :input_html => {:rows => 2}
    %hr
    = f.simple_fields_for :contents do |content|
      %h6
        New Content
      = content.input :title, :label => "Content title"
      = content.input :content_body, as: :text
      = content.input :sq_no, :label => "Sequence number"
      = content.input :topic_content_file_name, :label => "Upload Audio Mp3 File" do
        = content.input_field :topic_content_file_name, :readonly => true, id: "#{content.object.id}_audio_file"
        %span.btn.btn-success.fileinput-button
          %i.icon-plus.icon-white
          %span Browse...
          = content.input_field :topic_content, :class => "mp3"
        - if params[:controller] == "topics" && params[:action] == "edit" or params[:action] == "update" 
          %span.btn.btn-danger.delete
            %i.icon-trash.icon-white
            = link_to 'Delete', remove_mp3_file_path(@level, content.object.id), method: :put, data: { confirm: 'Are you sure to remove audio file?' }, style: 'color:#FFFFFF;', :class => "lnkdelete", :remote => true 
      = content.input :content_audio_file_name, :label => "Upload Audio Ogg File" do
        = content.input_field :content_audio_file_name, :readonly => true, id: "#{content.object.id}_ogg_file"
        %span.btn.btn-success.fileinput-button
          %i.icon-plus.icon-white
          %span Browse...
          = content.input_field :content_audio, :class => "ogg"               
        - if params[:controller] == "topics" && params[:action] == "edit" or params[:action] == "update" 
          %span.btn.btn-danger.delete
            %i.icon-trash.icon-white
            = link_to 'Delete', remove_ogg_file_path(content.object.id), method: :put, data: { confirm: 'Are you sure to remove audio file?' }, style: 'color:#FFFFFF;', :class => "lnkdelete", :remote => true
      %br
      = content.input :transcript, as: :ckeditor, :input_html => {:ckeditor => {:toolbar => 'mini'}}
      %br
      %hr           
      = content.simple_fields_for :questions do |question|
        %h6 New Question
        NOTE: minimum 3 options required
        = question.input :question_type, :collection => ["Simple", "Medium", "Hard"],
                         :prompt => "Select question type",
                         :input_html => {:id => "ddr_question_type"}
        = question.input :sq_no,  :label => "Sequence number"
        = question.input :query
        = question.simple_fields_for :options do |option|
          %h6 Option
          = option.input :label
          = option.input :is_valid, as: :boolean
          %br
          .pull-right= option.link_to_remove "Remove this option"
          %hr
        = question.link_to_add  question.object.options.count > 0? "Add More Options" :"Add Option", :options, :class => 'pull-right more_options'
        %br
        .pull-right= question.link_to_remove "Remove this question"
        %hr
      = content.link_to_add  content.object.questions.count > 0? "Add More Questions" :"Add questions", :questions, :class => 'btn btn-info more_question'
      .pull-right= content.link_to_remove "Remove this content"
    = f.link_to_add f.object.contents.count > 0 ?  "Add More Content" : "Add Content", :contents, :class => 'btn btn-info more_content'

  .form-actions
    = f.button :submit, class: 'btn btn-large btn-success'
    = link_to "Cancel", level_topics_path(@level), class: 'btn btn-large btn-success'    

app/views/topics/attempt_question.js.haml
- if @answer.is_valid == true
  $("#q_#{@question.id} .btn").hide()
  -@question.options.each do |opt| 
    $("#question_options_#{opt.id}").hide()
  $("#answer_#{@question.id}").html('<p>Congratulations! your answer is correct</p>')
- else
  $("#answer_#{@question.id}").html('<p>Sorry! your answer is wrong</p>')

app/views/topics/edit.html.haml
%h1.delta Edit topic for #{@level.level_name} level
.content
  = render 'form'

app/views/topics/index.html.haml
- content_for :javascript do
  = javascript_include_tag 'topics'
%h1.delta Topic Details for #{@level.level_name} level 
%table.table
  %tr
    %th Title
    %th Description
    %th

  - @topics.each do |topic|
    %tr  
      %td= topic.title
      %td= topic.description
      %td= link_to "Edit", edit_level_topic_path(@level, topic), :class => 'btn btn-mini'    
      %td= link_to "Show", level_topic_path(@level, topic), :class => 'btn btn-mini'

= link_to "New topic", new_level_topic_path, class: "btn btn-large"
= link_to "BACK" , levels_list_path, class: "btn btn-large"

app/views/topics/new.html.haml
%h1.delta New topic for #{@level.level_name} level 
.content
  = render 'form'

app/views/topics/remove_mp3_file.js.haml
$("##{params[:content_id]}_audio_file").val('')

app/views/topics/remove_ogg_file.js.haml
$("##{params[:content_id]}_ogg_file").val('')

app/views/topics/show.html.haml
- content_for :javascript do
  = javascript_include_tag 'topics',  'mediaelement_rails', 'mediaelement-and-player.min', 'tabPanel'
.topic
  .row
    .span8.offset2
      - @contents.each do |content|
        %h1.beta.topic-title
          = @topic.title
        %section.topic
          .row
            .audio
              - if browser.firefox? or browser.chrome? 
                =audio_tag content.content_audio, autoplay: false, controls: true, "aria-hidden" => "true"
              -elsif browser.ie?
                =audio_tag content.topic_content, autoplay: false, controls: true, "aria-hidden" => "true"
        %br
        .row
          .tabbable.tabs-left.topic-details.colored-block{:id => "tabpanel", :role => "application"}
            %ul.nav.nav-tabs{:role => "tablist"}
              %li.tab{:id => "s_tab", :role => "tab", "aria-owns" => "s_#{content.id.to_s}",
                              "aria-controls" => "s_#{content.id.to_s}"}
                %a{"data-toggle" => "tab", :href => "#s_#{content.id.to_s}"} Summary
              %li.tab.active{:id => "t_tab", :role => "tab", "aria-owns" => "t_#{content.id.to_s}",
                              "aria-selected" => "true", "aria-controls" => "t_#{content.id.to_s}"}
                %a{"data-toggle" => "tab", :href => "#t_#{content.id.to_s}"} Transcript
              %li.tab{:id => "test_tab", :role => "tab", "aria-owns" => "test_#{content.id.to_s}", "aria-controls" => "test_#{content.id.to_s}"}
                %a{"data-toggle" => "tab", :href => "#test_#{content.id.to_s}"} Take test
            .tab-content
              .tab-pane.summary{ :id => "s_#{content.id.to_s}", :role => "tabpanel", "aria-labelledby" => "s_tab"}
                %h3{"tabindex" => "0"} Summary
                = raw markdown content.content_body
              .tab-pane.transcript.active{:id => "t_#{content.id.to_s}", :role => "tabpanel", "aria-labelledby" => "t_tab"}
                %h3{"tabindex" => "0"} Transcript 
                = raw content.transcript
              .tab-pane.test{:id =>"test_#{content.id.to_s}", :role => "tabpanel", "aria-labelledby" => "t_tab"}
                %h3{"tabindex" => "0"} Take test
                - if user_signed_in?
                  %p 
                  - content.questions.each_index do |index|
                    - question = content.questions[index]
                    .span5.question{:id => "q_#{question.id}"}
                      %b 
                        =raw markdown question.query
                      - attempt = Attempt.where(:question => question, :user => current_user).first if current_user.attempts.count > 0
                      = simple_form_for question, :url => attempt_question_path(question), remote: true do |f|
                        .control-group
                          .controls
                            %br
                            %br
                            - if attempt == nil or attempt.solved == false
                              = f.collection_radio_buttons :options, question.options.collect{|opt| [opt.id, opt.label]}, :first, :last
                              = f.submit 'Submit', :class => 'btn'
                              %p{:id => "answer_#{question.id}"}
                            - else
                              - question.options.each do |option|
                                = f.label option.label
                - else
                  %p
                    %b To take test please #{link_to "sign in", new_user_session_path} or #{link_to "sign up", new_user_registration_path} 

      %br             
      .pull-right= link_to "BACK", level_path(@level), :class => "btn"
  = render_shareable :url => request.url