config/routes.rb
Brails::Application.routes.draw do

  get "home/index"
  devise_for :users, :path_names => {
    :sign_in => 'login', 
    :sign_out => 'logout', 
    :password => 'secret', 
    :confirmation => 'verification',
    :root_path => 'home#index' 
  }

  resources :users
  resources :requests
  resources :levels do
    resources :topics 
    resources :bonus_rounds
  end  

  match '/topics/attempt_question/:question_id' => 'topics#attempt_question', as: :attempt_question
  match '/level/attempt_question/:question_id' => 'levels#attempt_bonus_question', as: :attempt_bonus_question
  match '/users/:user_id/profile' => 'users#profile', :via => [:get, :post], as: :profile
  match '/levels_list' => 'levels#levels_list', :via => :get, as: :levels_list
  match '/nominate' => 'home#nominate', :via => [:get, :post], as: :nominate
  match 'nominate_list' => 'home#nominate_list', :via => :get, as: :nominate_list
  match '/feedback' => 'home#feedback', :via => [:get, :post], as: :feedback
  match '/feedback_list' => 'home#feedback_list', :via => :get, as: :feedback_list
  put '/levels/:level_id/content/:content_id' => 'topics#remove_mp3_file', as: :remove_mp3_file
  put '/content/:content_id' => 'topics#remove_ogg_file', as: :remove_ogg_file

  root :to => 'levels#index'

  match ':action' => 'static#:action'
end

app/models/request.rb
class Request
  include Mongoid::Document

  field :title, type: String
  field :body, type: String
  field :status, type: String

  validates :title, :body, :status, :presence => true

  has_many :comments
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/index.html.haml
%h1 Request Details
%table
  %tr
    %th Title
    %th Body
    %th Status    
  %tr
    %td plz expalin briefly
    %td Introduction of Java
    %td tell me
    %td= link_to "show", show_request_path
    
  %tr
    %td i didn't get this point
    %td Introduction of c++
    %td suggest me
    %td= link_to "show", show_request_path

= link_to "Back", requests_path   

app/views/requests/new.html.haml
%label *Title
%input 
%br
%label *Body
%input
%br
%label *Status
%input
%br
%button create Suggest

app/views/requests/show.html.haml
%h1 REQUEST DETAILS
%table
  %tr
    %th Title
    %th Body
    %th Status
    
  %tr
    %td dont get this point
    %td suggest me
    %td please explain us..
    
= link_to "Back", show_request_path   