config/routes.rb
Brails::Application.routes.draw do

  get "home/index"
  devise_for :users, :path_names => {
    :sign_in => 'login', 
    :sign_out => 'logout', 
    :password => 'secret', 
    :confirmation => 'verification',
    :root_path => 'home#index' 
  }

  resources :users
  resources :requests
  resources :levels do
    resources :topics 
    resources :bonus_rounds
  end  

  match '/topics/attempt_question/:question_id' => 'topics#attempt_question', as: :attempt_question
  match '/level/attempt_question/:question_id' => 'levels#attempt_bonus_question', as: :attempt_bonus_question
  match '/users/:user_id/profile' => 'users#profile', :via => [:get, :post], as: :profile
  match '/levels_list' => 'levels#levels_list', :via => :get, as: :levels_list
  match '/nominate' => 'home#nominate', :via => [:get, :post], as: :nominate
  match 'nominate_list' => 'home#nominate_list', :via => :get, as: :nominate_list
  match '/feedback' => 'home#feedback', :via => [:get, :post], as: :feedback
  match '/feedback_list' => 'home#feedback_list', :via => :get, as: :feedback_list
  put '/levels/:level_id/content/:content_id' => 'topics#remove_mp3_file', as: :remove_mp3_file
  put '/content/:content_id' => 'topics#remove_ogg_file', as: :remove_ogg_file

  root :to => 'levels#index'

  match ':action' => 'static#:action'
end

app/models/level.rb
class Level
  include Mongoid::Document
  include Mongoid::Slug

  field :level_number, type: Integer
  field :level_name, type: String

  slug :level_name

  has_many :topics, dependent: :destroy 
  has_many :questions, dependent: :destroy 
  accepts_nested_attributes_for :questions, allow_destroy: true

  #validation
  validates :level_number, :level_name, :presence => true
  validates :level_number, :numericality => {:only_integer => true,  :greater_than => 0 }
  
  # Use counter_cache
  def calculate_coins_count
    topics.includes(:contents).inject(0) do |count, topic|
      count + topic.contents.inject(0) do |count, content|
        count + content.questions.inject(0) do |count, question|
          count + H_COOKIES[question.question_type]
	end
      end
    end
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource :level, :except => [:index, :show]
 

  def index
    @levels = Level.all.order_by("level_number ASC")
  end

  def levels_list
    @levels = Level.all.order_by("level_number ASC")
  end

  def show
    @count = 0
    @level = Level.find(params[:id])
    @topics = @level.topics
  end

  def new
    @level = Level.new
  end

  def create		
    @level = Level.new(params[:level])
    respond_to do |format|
      if @level.save
        format.html { redirect_to levels_list_path, notice: 'level created successfully.' }
        format.json { render json: @level, status: :created, location: @level }
      else
        format.html { render action: "new"}
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @level = Level.find(params[:id])
  end

  def update
    @level = Level.find(params[:id])
    respond_to do |format|
      if @level.update_attributes(params[:level])
        format.html { redirect_to levels_list_path, notice: 'level was successfully updated.' }
        format.json { render json: @level, status: :updated, location: @level }
      else
        format.html { render action: "edit"}
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @level = Level.find(params[:id])
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_list_path, notice: "Level was deleted successfully."}
      format.json { head :no_content }
    end
  end

  def attempt_bonus_question
    @question = Question.find(params[:question_id])
    @answer = @question.options.where(:_id => params["question"]['options']).try(:first) if params['question'].present?
    @attempt = Attempt.find_or_create_by(:user => current_user, :question => @question)
    if @answer.is_valid and @attempt.increase_count == 0
      @attempt.update_attributes({solved: true, coins: H_COOKIES[@question.question_type]})
    elsif @answer.is_valid and @attempt.increase_count > 0
      coins = (H_COOKIES[@question.question_type] / @attempt.increase_count ).round
      @attempt.update_attributes({solved: true, coins: coins})
    else
      @attempt.inc(:increase_count, 1)
    end
  end

  def calculate_coins(level_id)
    @level = Level.find_by(:id => level_id)
    @level.topics.includes(:contents).inject(0) do |count, topic|
      count + topic.contents.inject(0) do |count, content|
        count + content.questions.inject(0) do |count, question|
          return count + H_COOKIES[question.question_type]
	      end
      end
    end
  end
end

app/helpers/levels_helper.rb
module LevelsHelper

  def calculate_usercoins_bonusround(level)
    level.questions.inject(0) do |count, question|
      count + question.attempts.where(user_id: current_user.id).inject(0)do |count, attempt|
        count + attempt.coins
      end
    end
  end
  
  def calculate_totalcoins_bonusround(level)
    level.questions.inject(0) do |count, question|
      count + H_COOKIES[question.question_type] 
    end
  end

end 

app/views/levels/_form.html.haml
- content_for :javascript do
  = javascript_include_tag 'validations', 'levels', 'nested_form'
= simple_nested_form_for @level, html: {:class => 'form-horizontal'} do |f|
  = f.error_notification
  %p#errorcontainer

  .form-inputs
    = f.input :level_number
    = f.input :level_name
    = f.simple_fields_for :questions do |question|
      = question.input :level_id, :as => :hidden, :input_html => {:value => "#{@level.id}"} 
      = question.input :question_type, :collection => ["Simple", "Medium", "Hard"], :prompt => "Select question type"
      = question.input :sq_no, :label => "Sequence number"
      = question.input :query
      = question.simple_fields_for :options do |option|
        = option.input :label
        = option.input :is_valid, as: :boolean
        .pull-right= option.link_to_remove "Remove this option", :class => 'btn btn-success'
      .pull-right= question.link_to_remove "Remove this question", :class => 'btn btn-success'
      = question.link_to_add question.object.options.count > 0 ? "Add More Option" : "Add an option", :options, :class => 'btn btn-success more_option'
    = f.link_to_add f.object.questions.count > 0 ?  "Add More Bonus Round Question" : "Add bonus round questions", :questions, :class => 'btn btn-success more_question'


  .form-actions
    = f.button :submit, class: 'btn btn-large btn-success'
    = link_to "Cancel", levels_list_path, class: 'btn btn-large btn-success'

app/views/levels/attempt_bonus_question.js.haml
- if @answer.is_valid == true
  $("#q_#{@question.id} .btn").hide()
  -@question.options.each do |opt|
    $("#question_options_#{opt.id}").hide()
  $("#answer_#{@question.id}").html('<p>Congratulations! your answer is correct</p>')
- else
  $("#answer_#{@question.id}").html('<p>Sorry! your answer is wrong</p>')

app/views/levels/edit.html.haml
%h1 Edit level
.content
  = render 'form'

app/views/levels/index.html.haml
- content_for :javascript do
  = javascript_include_tag 'levels', 'handle_aria_event'
#grid-wrapper.lessons{:role => "application"}
  %h1 Select level
  #game-levels.no-focus{role: 'grid', tabindex: '0'}
    - (1..@levels.count).to_a.each_slice(2).each_with_index do |levels, row_index|
      .row-fluid{role: 'row'}
        - levels.each_with_index do |level, col_index|
          - @level = @levels[level-1]
          - level_coins_count = @level.calculate_coins_count
          .gridcell.grid-cell.span6{id: "row_#{row_index}_col_#{col_index}", role: 'gridcell',
                    "aria-labelledby"=> "level_number_#{@level.level_number}",
                    "aria-describedby"=>"level_caption_#{@level.level_number}"}
            .row-fluid
              .span4.summary-coin.colored-block
                = "#{level_coins_count}"
              .span8.lesson-summary.colored-block.no-focus
                %header{id: "level_number_#{@level.level_number}"}
                  .counter{class: "counter-#{@level.level_number}"}
                  = @level.level_number
                %p.description{id: "level_caption_#{@level.level_number}"}
                  = link_to @level.level_name, level_path(@level)

app/views/levels/levels_list.html.haml
- content_for :javascript do
  = javascript_include_tag 'levels'
%h1.delta Display levels
%table.table
  %tr
    %th Level name
    %th Level number
    %th 
    %th

  - @levels.each do |level|
    %tr
      %td= link_to level.level_name, level_topics_path(level)
      %td= level.level_number
      %td= link_to "Edit", edit_level_path(level), :class => 'btn btn-mini'
      %td= link_to "Destroy", level, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini' 

= link_to "New level", new_level_path, class: "btn btn-large"
= link_to "Cancel", levels_path, class: "btn btn-large"

app/views/levels/new.html.haml
%h1 New level
.content
  = render 'form'

app/views/levels/show.html.haml
- content_for :javascript do
  = javascript_include_tag 'levels', 'handle_aria_event'
.level
  .row
    .span6
      .row-fluid
        .counter{class: "counter-7"}
        %h1.gamma.level-header #{@level.level_name}
  .row
    .span3.level-scoring
      .score-wrapper
        %ul.unstyled.score.large
          - @level.calculate_coins_count.times do |count|
            %li.score-indicator{ :class => "#{'complete' if count < @topics.collect{|topic| won_topic_coins(topic)}.inject(:+)}"}
        %span.delta  #{@topics.collect{|topic| won_topic_coins(topic)}.inject(:+)} of #{@level.calculate_coins_count} coins  won
    .span9
      - @topics.each do |topic|
        .row-fluid.level-topic-wrapper.colored-block
          .span9
            .row-fluid.level-topic
              .span3
                .score-wrapper
                  %ul.unstyled.score
                    - topic_coins = topic_calculate_coins(topic).to_i
                    - topic_coins.times do |count|
                      %li.score-indicator{ :class => "#{'complete' if count < won_topic_coins(topic)}"}

              .span9.topic-details
                %h2.delta= topic.title
                %p.topic-description= topic.description
                - if topic.contents.count == 0
                  %p.topic-description Coming soon
                - else
                  = link_to "Start topic", level_topic_path(@level, topic), class: "btn btn-start-topic"
          .span3
            - if topic_questions_count(topic) == Attempt.where(:user => current_user, :topic => topic, :solved => true).collect(&:solved).size
              .topic-score.right
              - @count = @count + 1
            - else
              .topic-score.wrong
.row{:style => "margin-top: 50px" }
  -if @level.questions? and current_user.present?
    .span3.level-scoring
      .score-wrapper
        %ul.unstyled.score.large
          - calculate_totalcoins_bonusround(@level).times do |count|
            %li.score-indicator{ :class => "#{'complete' if count < calculate_usercoins_bonusround(@level)}"}
        %span.delta   #{calculate_usercoins_bonusround(@level)} of #{calculate_totalcoins_bonusround(@level)} coins won
    .span9
      - if @level.topics.count == @count
        %input{:type => "button",:class => "btn-bonus-round unlocked",:id => "bonus_round_unlocked", :value => "Bonus Round Unlocked"}
      - else
        %button{:disabled => "true", :class => "btn-bonus-round"} Bonus Round Locked
      #bonus_round{:style => "display: none"}
        %h3 Bonus Round Questions
        - @level.questions.each do |question|
        - attempt = Attempt.where(:question => question, :user => current_user).first if current_user.attempts.count  > 0
          .span5.question{:id => "q_#{question.id}"}
            %br
            QUESTION:
            = question.query
            %br
            %br
            = simple_form_for question, :url => attempt_bonus_question_path(question), remote: true do |f|
              .control-group
                .controls
                  OPTIONS:
                  %br
                  - if attempt == nil or attempt.solved == false
                    = f.collection_radio_buttons :options, question.options.collect{|opt| [opt.id, opt.label]}, :first,     :last
                    = f.submit 'Submit', :class => 'btn'
                    %p{:id => "answer_#{question.id}"}
                  - else
                    - question.options.each do |option|
                      = f.label option.label
  = render_shareable :url => request.url
  .pull-right
    = link_to "Back", levels_path, class: 'btn btn-large'