config/routes.rb
Brails::Application.routes.draw do

  get "home/index"
  devise_for :users, :path_names => {
    :sign_in => 'login', 
    :sign_out => 'logout', 
    :password => 'secret', 
    :confirmation => 'verification',
    :root_path => 'home#index' 
  }

  resources :users
  resources :requests
  resources :levels do
    resources :topics 
    resources :bonus_rounds
  end  

  match '/topics/attempt_question/:question_id' => 'topics#attempt_question', as: :attempt_question
  match '/level/attempt_question/:question_id' => 'levels#attempt_bonus_question', as: :attempt_bonus_question
  match '/users/:user_id/profile' => 'users#profile', :via => [:get, :post], as: :profile
  match '/levels_list' => 'levels#levels_list', :via => :get, as: :levels_list
  match '/nominate' => 'home#nominate', :via => [:get, :post], as: :nominate
  match 'nominate_list' => 'home#nominate_list', :via => :get, as: :nominate_list
  match '/feedback' => 'home#feedback', :via => [:get, :post], as: :feedback
  match '/feedback_list' => 'home#feedback_list', :via => :get, as: :feedback_list
  put '/levels/:level_id/content/:content_id' => 'topics#remove_mp3_file', as: :remove_mp3_file
  put '/content/:content_id' => 'topics#remove_ogg_file', as: :remove_ogg_file

  root :to => 'levels#index'

  match ':action' => 'static#:action'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to "/", :alert => exception.message
  end

  protect_from_forgery
  #TODO: uncomment during development
#  before_filter :authenticate_user!, :except => [:index, :show]

  helper_method :won_topic_coins, :topic_calculate_coins, :topic_questions_count

  def won_topic_coins(topic)
    topic.attempts.where(:user => current_user).collect{|attempt| attempt.coins}.inject(:+) || 0
  end

  def topic_calculate_coins(topic)
    topic.contents.includes(:questions).inject(0) do |count, content|
      count + content.questions.inject(0) do |count, question|
        count + H_COOKIES[question.question_type]
      end
    end
  end

  def topic_questions_count(topic)
    topic.contents.includes(:questions).inject(0) do |questions_count, content|
      questions_count + content.questions.count
    end
  end

  def after_sign_in_path_for(resource)
    if resource && resource.sign_in_count == 1
      root_path
    else
      levels_path
    end
  end


  protected
  def authenticate_inviter!
   # authenticate_user!(:force => true)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_flash_messages(options = {})
    ret = []
    flash.each do |key, value|
      ret << content_tag( :div, {class: "flash alert alert-#{key} global", id: "flash-#{key}"}) do
        content = haml_tag "a.close", "data-dismiss" => "alert" 
        haml_concat value
      end
    end
    return_string = ret.join("\n")
    return return_string.respond_to?(:html_safe) ? return_string.html_safe : return_string
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true, 
    :hard_wrap => true)
    options = {
    :fenced_code_blocks => true,
    :no_intra_emphasis => true,
    :autolink => true,
    :superscript => true,
    :strikethrough => true,
    :no_styles => true
    } 
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/application/_footer.html.haml
.row-fluid
  .span4
    %ul.nav
      %li
        %p Knowledge Partner
      %li
        %a.josh{:href => "http://joshsoftware.com"}
          %img{:src =>'/images/Josh.svg', :alt => 'Josh software', :width => "100px"}
  .span4
    %ul.nav
      %li
        %p Developed by
      %li
        %a{:href => "http://techvision.net.in"}
          %img{:src =>'/images/techvision4.jpg', :alt => 'TechVision', :width => "125px"}
  .span4
    %ul.nav
      %li
        %p Hosting Partner
      %li
        %a{:href => "http://www.rackspace.com/"}
          %img{:src =>'/images/Rackspace_Cloud_Company_Logo_clr_300x109.jpg', :alt => 'Rackspace', :width => "100px"}

app/views/application/_header.html.haml
#navbar-top
  .navbar.navbar-inverse.navbar-fixed-top
    .navbar-inner
      .container{:role => "navigation"}
        .row
          .brand
            = link_to "Brails", "/"
          - if user_signed_in?
            %ul.nav  
              - if current_user.roles == "Admin"
                %li
                  = link_to "Level", levels_list_path
          .span7.pull-right
            %ul.nav.pull-right
              %li
                = link_to "Nominate", nominate_path
              %li
                = link_to "Feedback", feedback_path
              - if user_signed_in?
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", "aria-haspopup" => "true"}                  
                    = current_user.email
                    %b.caret
                  %ul.dropdown-menu
                    - if current_user.profile.nil?
                      %li= link_to 'New profile', edit_user_path(current_user) 
                    - else
                      %li= link_to 'My profile', profile_path(current_user)
                    %li=  link_to 'Logout', destroy_user_session_path, :method => :delete
              - else
                %li
                  = link_to 'Sign up', new_user_registration_path
                %li
                  = link_to 'Sign in', new_user_session_path